#! usr\bin\env python3
# 

import sqlite3

class Sqlite(object):

    def __init__(self,DBname,SQL):
        self.DBname=DBname
        self.SQL=SQL
        
    def get_connection(self):
        self.conn=sqlite3.connect(self.DBname)
        return self.conn

    def get_cursor(self):
        self.get_connection()
        self.cu=self.conn.cursor()
        return self.cu

    def insert_info(self):
        self.get_connection()
        self.get_cursor()
        self.cu.execute("insert into pictures (id,name,NOs,numbers,url,year,date)\
values (?,?,?,?,?,?,?)",(self.SQL))
        self.conn.commit()
        
    def show_info(self):
        self.get_connection()
        self.get_cursor()
        self.c=self.cu.execute("select * from pictures")
        return list(self.cu.fetchall())
